import { PrismaClient } from "@prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";

const adapter = new PrismaLibSql({ url: "file:./prisma/dev.db" });
const prisma = new PrismaClient({ adapter });

const influencers = [
  // Beauty & Skincare
  {
    instagramHandle: "glowwithsarah",
    name: "Sarah Chen",
    niche: "Beauty & Skincare",
    subNiche: "Clean Beauty",
    followerCount: 127500,
    followingCount: 892,
    engagementRate: 4.2,
    avgLikes: 5355,
    avgComments: 234,
    avgShares: 89,
    bio: "Clean beauty advocate | Skincare routines that actually work | LA based",
    profilePicUrl: "https://i.pravatar.cc/150?img=1",
    location: "Los Angeles, CA",
    audienceAgeRange: "24-35",
    audienceGender: "85% Female",
    audienceLocation: "US 68%, UK 12%, Canada 8%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["Versed", "Youth to the People", "Glow Recipe"]),
    tags: JSON.stringify(["clean beauty", "skincare", "wellness", "natural", "cruelty-free"]),
    priceRange: "300-800",
    isVerified: false,
  },
  {
    instagramHandle: "makeup_bymia",
    name: "Mia Rodriguez",
    niche: "Beauty & Makeup",
    subNiche: "Drugstore Makeup",
    followerCount: 89200,
    followingCount: 1205,
    engagementRate: 5.8,
    avgLikes: 5174,
    avgComments: 312,
    avgShares: 145,
    bio: "Makeup artist & educator | Drugstore looks on a budget | NYC",
    profilePicUrl: "https://i.pravatar.cc/150?img=5",
    location: "New York, NY",
    audienceAgeRange: "18-28",
    audienceGender: "92% Female",
    audienceLocation: "US 72%, Mexico 8%, Colombia 6%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["e.l.f.", "NYX", "Milani", "ColourPop"]),
    tags: JSON.stringify(["makeup", "beauty", "drugstore", "tutorial", "glam"]),
    priceRange: "200-500",
    isVerified: false,
  },
  {
    instagramHandle: "skincarebylinh",
    name: "Linh Nguyen",
    niche: "Skincare",
    subNiche: "Korean Skincare",
    followerCount: 203000,
    followingCount: 445,
    engagementRate: 3.1,
    avgLikes: 6293,
    avgComments: 189,
    avgShares: 67,
    bio: "K-beauty obsessed | Glass skin routine | Skincare science simplified",
    profilePicUrl: "https://i.pravatar.cc/150?img=9",
    location: "San Francisco, CA",
    audienceAgeRange: "22-34",
    audienceGender: "88% Female",
    audienceLocation: "US 60%, South Korea 10%, Australia 7%",
    contentTypes: JSON.stringify(["posts", "reels", "stories"]),
    pastBrands: JSON.stringify(["COSRX", "Laneige", "Some By Mi", "Innisfree"]),
    tags: JSON.stringify(["kbeauty", "skincare", "glass skin", "korean beauty", "routine"]),
    priceRange: "500-1200",
    isVerified: true,
  },

  // Fitness & Wellness
  {
    instagramHandle: "fitwithjordan",
    name: "Jordan Hayes",
    niche: "Fitness & Wellness",
    subNiche: "Home Workouts",
    followerCount: 156000,
    followingCount: 678,
    engagementRate: 4.7,
    avgLikes: 7332,
    avgComments: 421,
    avgShares: 198,
    bio: "NASM certified | Home workout specialist | Making fitness accessible for everyone",
    profilePicUrl: "https://i.pravatar.cc/150?img=12",
    location: "Austin, TX",
    audienceAgeRange: "25-40",
    audienceGender: "55% Female, 45% Male",
    audienceLocation: "US 78%, Canada 10%, Australia 5%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["Gymshark", "Bowflex", "MyProtein", "Optimum Nutrition"]),
    tags: JSON.stringify(["fitness", "workout", "health", "wellness", "motivation", "home gym"]),
    priceRange: "400-900",
    isVerified: false,
  },
  {
    instagramHandle: "yoga_with_priya",
    name: "Priya Sharma",
    niche: "Yoga & Mindfulness",
    subNiche: "Prenatal Yoga",
    followerCount: 78400,
    followingCount: 934,
    engagementRate: 6.3,
    avgLikes: 4939,
    avgComments: 356,
    avgShares: 234,
    bio: "RYT 500 Yoga teacher | Prenatal & postnatal specialist | Mindful living | Mom of 2",
    profilePicUrl: "https://i.pravatar.cc/150?img=15",
    location: "Denver, CO",
    audienceAgeRange: "28-42",
    audienceGender: "94% Female",
    audienceLocation: "US 65%, UK 12%, India 8%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["Manduka", "Alo Yoga", "Thrive Market"]),
    tags: JSON.stringify(["yoga", "wellness", "mindfulness", "prenatal", "meditation", "mom"]),
    priceRange: "200-600",
    isVerified: false,
  },

  // Food & Nutrition
  {
    instagramHandle: "healthybites_emma",
    name: "Emma Wilson",
    niche: "Food & Nutrition",
    subNiche: "Healthy Meal Prep",
    followerCount: 245000,
    followingCount: 512,
    engagementRate: 3.8,
    avgLikes: 9310,
    avgComments: 445,
    avgShares: 312,
    bio: "Registered Dietitian | Easy healthy recipes | Meal prep queen | Plant-forward eating",
    profilePicUrl: "https://i.pravatar.cc/150?img=20",
    location: "Chicago, IL",
    audienceAgeRange: "26-40",
    audienceGender: "76% Female",
    audienceLocation: "US 70%, Canada 12%, Australia 6%",
    contentTypes: JSON.stringify(["posts", "reels", "stories"]),
    pastBrands: JSON.stringify(["Thrive Market", "Vital Farms", "Simple Mills", "Siete"]),
    tags: JSON.stringify(["healthy eating", "meal prep", "nutrition", "recipes", "food", "dietitian"]),
    priceRange: "600-1500",
    isVerified: true,
  },
  {
    instagramHandle: "vegan_by_marcus",
    name: "Marcus Thompson",
    niche: "Food & Lifestyle",
    subNiche: "Vegan Living",
    followerCount: 112000,
    followingCount: 823,
    engagementRate: 4.4,
    avgLikes: 4928,
    avgComments: 287,
    avgShares: 156,
    bio: "Plant-based chef | Making vegan food delicious | Cookbook author | Atlanta",
    profilePicUrl: "https://i.pravatar.cc/150?img=25",
    location: "Atlanta, GA",
    audienceAgeRange: "22-38",
    audienceGender: "62% Female, 38% Male",
    audienceLocation: "US 74%, UK 9%, Canada 7%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["Oatly", "Beyond Meat", "Kite Hill", "Miyoko's"]),
    tags: JSON.stringify(["vegan", "plantbased", "cooking", "food", "sustainability", "chef"]),
    priceRange: "300-700",
    isVerified: false,
  },

  // Fashion & Style
  {
    instagramHandle: "style_by_zoe",
    name: "Zoe Mitchell",
    niche: "Fashion & Style",
    subNiche: "Affordable Fashion",
    followerCount: 189000,
    followingCount: 1102,
    engagementRate: 3.9,
    avgLikes: 7371,
    avgComments: 334,
    avgShares: 123,
    bio: "Fashion on a budget | Outfit ideas daily | Inclusive sizing | Portland",
    profilePicUrl: "https://i.pravatar.cc/150?img=30",
    location: "Portland, OR",
    audienceAgeRange: "20-32",
    audienceGender: "89% Female",
    audienceLocation: "US 80%, Canada 8%, UK 5%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["ASOS", "Quay", "Adidas", "Target Style"]),
    tags: JSON.stringify(["fashion", "ootd", "style", "affordable", "outfit", "inclusive"]),
    priceRange: "200-600",
    isVerified: false,
  },
  {
    instagramHandle: "luxe_with_isabella",
    name: "Isabella Fontaine",
    niche: "Luxury Fashion",
    subNiche: "Sustainable Luxury",
    followerCount: 67800,
    followingCount: 345,
    engagementRate: 5.2,
    avgLikes: 3526,
    avgComments: 198,
    avgShares: 45,
    bio: "Sustainable luxury advocate | Investment pieces that last | Miami & NYC",
    profilePicUrl: "https://i.pravatar.cc/150?img=35",
    location: "Miami, FL",
    audienceAgeRange: "30-45",
    audienceGender: "83% Female",
    audienceLocation: "US 65%, UK 15%, UAE 8%",
    contentTypes: JSON.stringify(["posts", "stories", "reels"]),
    pastBrands: JSON.stringify(["Cuyana", "Everlane", "Reformation", "Veja"]),
    tags: JSON.stringify(["luxury", "sustainable fashion", "investment pieces", "style", "minimalist"]),
    priceRange: "500-2000",
    isVerified: false,
  },

  // Home & Lifestyle
  {
    instagramHandle: "home_with_kate",
    name: "Kate Anderson",
    niche: "Home & Lifestyle",
    subNiche: "Interior Design",
    followerCount: 334000,
    followingCount: 678,
    engagementRate: 2.9,
    avgLikes: 9686,
    avgComments: 423,
    avgShares: 567,
    bio: "Interior designer | Making beautiful homes accessible | DIY tips & tricks | Seattle",
    profilePicUrl: "https://i.pravatar.cc/150?img=40",
    location: "Seattle, WA",
    audienceAgeRange: "28-45",
    audienceGender: "78% Female",
    audienceLocation: "US 72%, Canada 10%, Australia 7%",
    contentTypes: JSON.stringify(["posts", "reels", "stories"]),
    pastBrands: JSON.stringify(["Crate & Barrel", "Article", "West Elm", "IKEA"]),
    tags: JSON.stringify(["home decor", "interior design", "DIY", "home", "lifestyle", "design"]),
    priceRange: "700-2000",
    isVerified: true,
  },

  // Parenting & Family
  {
    instagramHandle: "momlife_with_ashley",
    name: "Ashley Cooper",
    niche: "Parenting & Family",
    subNiche: "Millennial Moms",
    followerCount: 143000,
    followingCount: 892,
    engagementRate: 5.1,
    avgLikes: 7293,
    avgComments: 534,
    avgShares: 289,
    bio: "Mom of 3 | Real talk about motherhood | Baby gear reviews | Dallas",
    profilePicUrl: "https://i.pravatar.cc/150?img=45",
    location: "Dallas, TX",
    audienceAgeRange: "25-38",
    audienceGender: "96% Female",
    audienceLocation: "US 82%, Canada 7%, UK 5%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["UPPAbaby", "Honest Company", "Lovevery", "Ergobaby"]),
    tags: JSON.stringify(["mom", "parenting", "baby", "family", "motherhood", "toddler"]),
    priceRange: "300-800",
    isVerified: false,
  },

  // Pets
  {
    instagramHandle: "petparent_claire",
    name: "Claire Davies",
    niche: "Pets & Animals",
    subNiche: "Dog Lifestyle",
    followerCount: 98500,
    followingCount: 1234,
    engagementRate: 5.7,
    avgLikes: 5615,
    avgComments: 412,
    avgShares: 178,
    bio: "Dog mom x3 | Honest pet product reviews | Vet-approved content | Boston",
    profilePicUrl: "https://i.pravatar.cc/150?img=50",
    location: "Boston, MA",
    audienceAgeRange: "22-40",
    audienceGender: "72% Female",
    audienceLocation: "US 75%, Canada 12%, UK 7%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["Ollie", "The Farmer's Dog", "BarkBox", "Ruffwear"]),
    tags: JSON.stringify(["dogs", "pets", "petcare", "dogmom", "puppy", "doglife"]),
    priceRange: "250-600",
    isVerified: false,
  },

  // Tech & Gadgets
  {
    instagramHandle: "techreview_alex",
    name: "Alex Park",
    niche: "Technology",
    subNiche: "Consumer Tech",
    followerCount: 178000,
    followingCount: 567,
    engagementRate: 3.4,
    avgLikes: 6052,
    avgComments: 534,
    avgShares: 234,
    bio: "Honest tech reviews | Gadgets worth buying | Mobile photography | San Jose",
    profilePicUrl: "https://i.pravatar.cc/150?img=55",
    location: "San Jose, CA",
    audienceAgeRange: "20-35",
    audienceGender: "68% Male, 32% Female",
    audienceLocation: "US 65%, India 12%, UK 8%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["Anker", "Rode", "DJI", "Moment"]),
    tags: JSON.stringify(["tech", "gadgets", "review", "smartphone", "innovation", "apple"]),
    priceRange: "400-1000",
    isVerified: false,
  },

  // Sustainability & Eco
  {
    instagramHandle: "eco_living_nina",
    name: "Nina Green",
    niche: "Sustainability",
    subNiche: "Zero Waste Living",
    followerCount: 87300,
    followingCount: 756,
    engagementRate: 5.5,
    avgLikes: 4802,
    avgComments: 367,
    avgShares: 289,
    bio: "Zero waste advocate | Sustainable swaps for everyday life | Plastic-free journey | Portland",
    profilePicUrl: "https://i.pravatar.cc/150?img=60",
    location: "Portland, OR",
    audienceAgeRange: "22-38",
    audienceGender: "78% Female",
    audienceLocation: "US 68%, Canada 10%, UK 9%",
    contentTypes: JSON.stringify(["posts", "reels", "stories"]),
    pastBrands: JSON.stringify(["Package Free Shop", "Grove Collaborative", "Blueland", "EarthHero"]),
    tags: JSON.stringify(["sustainability", "zerowaste", "eco", "green", "plastic-free", "environment"]),
    priceRange: "150-400",
    isVerified: false,
  },

  // Coffee & Beverages
  {
    instagramHandle: "coffee_chronicles_james",
    name: "James Wu",
    niche: "Food & Beverage",
    subNiche: "Specialty Coffee",
    followerCount: 54200,
    followingCount: 432,
    engagementRate: 6.8,
    avgLikes: 3686,
    avgComments: 289,
    avgShares: 145,
    bio: "Coffee roaster & educator | Third wave coffee culture | Brewing guides & gear reviews",
    profilePicUrl: "https://i.pravatar.cc/150?img=65",
    location: "Seattle, WA",
    audienceAgeRange: "24-40",
    audienceGender: "58% Male, 42% Female",
    audienceLocation: "US 70%, Canada 10%, UK 8%",
    contentTypes: JSON.stringify(["posts", "reels"]),
    pastBrands: JSON.stringify(["Fellow", "Baratza", "Blue Bottle", "Trade Coffee"]),
    tags: JSON.stringify(["coffee", "specialty coffee", "brewing", "caffeine", "barista", "espresso"]),
    priceRange: "150-400",
    isVerified: false,
  },

  // Fitness - Running
  {
    instagramHandle: "run_with_rachel",
    name: "Rachel Kim",
    niche: "Fitness",
    subNiche: "Running & Marathon",
    followerCount: 76900,
    followingCount: 823,
    engagementRate: 5.9,
    avgLikes: 4537,
    avgComments: 312,
    avgShares: 167,
    bio: "Marathon runner | Running coach | Training plans & gear reviews | Boston qualifier | Chicago",
    profilePicUrl: "https://i.pravatar.cc/150?img=70",
    location: "Chicago, IL",
    audienceAgeRange: "26-42",
    audienceGender: "60% Female, 40% Male",
    audienceLocation: "US 76%, Canada 11%, UK 6%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["Brooks", "Garmin", "GU Energy", "Nuun"]),
    tags: JSON.stringify(["running", "marathon", "fitness", "run", "training", "runner"]),
    priceRange: "200-600",
    isVerified: false,
  },

  // Baby & Infant
  {
    instagramHandle: "newborn_essentials_jen",
    name: "Jennifer Martinez",
    niche: "Parenting",
    subNiche: "Newborn & Infant",
    followerCount: 112000,
    followingCount: 567,
    engagementRate: 5.4,
    avgLikes: 6048,
    avgComments: 489,
    avgShares: 312,
    bio: "NICU nurse turned mom blogger | Evidence-based parenting | Newborn must-haves | Phoenix",
    profilePicUrl: "https://i.pravatar.cc/150?img=75",
    location: "Phoenix, AZ",
    audienceAgeRange: "24-36",
    audienceGender: "97% Female",
    audienceLocation: "US 84%, Canada 7%, UK 4%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["SNOO", "DockATot", "Nanit", "Ollie Swaddle"]),
    tags: JSON.stringify(["newborn", "baby", "infant", "parenting", "momlife", "nursery"]),
    priceRange: "300-700",
    isVerified: false,
  },

  // Men's Grooming
  {
    instagramHandle: "grooming_with_david",
    name: "David Foster",
    niche: "Men's Grooming & Style",
    subNiche: "Beard Care",
    followerCount: 93400,
    followingCount: 678,
    engagementRate: 4.6,
    avgLikes: 4297,
    avgComments: 256,
    avgShares: 123,
    bio: "Men's grooming expert | Beard care routines | Honest product reviews | Nashville",
    profilePicUrl: "https://i.pravatar.cc/150?img=8",
    location: "Nashville, TN",
    audienceAgeRange: "22-40",
    audienceGender: "78% Male, 22% Female",
    audienceLocation: "US 79%, Canada 9%, UK 6%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["Beardbrand", "Tiege Hanley", "Every Man Jack", "Duke Cannon"]),
    tags: JSON.stringify(["grooming", "beard", "men", "skincare", "mancare", "style"]),
    priceRange: "200-500",
    isVerified: false,
  },

  // Nutrition Supplements
  {
    instagramHandle: "supplements_with_tom",
    name: "Tom Bradley",
    niche: "Health & Supplements",
    subNiche: "Sports Nutrition",
    followerCount: 134000,
    followingCount: 445,
    engagementRate: 4.1,
    avgLikes: 5494,
    avgComments: 378,
    avgShares: 189,
    bio: "Certified nutritionist | Supplement science | No BS fitness advice | Denver",
    profilePicUrl: "https://i.pravatar.cc/150?img=18",
    location: "Denver, CO",
    audienceAgeRange: "22-38",
    audienceGender: "65% Male, 35% Female",
    audienceLocation: "US 73%, Canada 11%, UK 8%",
    contentTypes: JSON.stringify(["reels", "posts"]),
    pastBrands: JSON.stringify(["Transparent Labs", "Legion Athletics", "Momentous", "AG1"]),
    tags: JSON.stringify(["supplements", "nutrition", "fitness", "protein", "health", "gym"]),
    priceRange: "300-800",
    isVerified: false,
  },

  // Travel & Adventure
  {
    instagramHandle: "adventures_with_sam",
    name: "Sam Rivera",
    niche: "Travel & Adventure",
    subNiche: "Budget Travel",
    followerCount: 267000,
    followingCount: 892,
    engagementRate: 2.7,
    avgLikes: 7209,
    avgComments: 489,
    avgShares: 678,
    bio: "Full-time traveler | Budget travel tips | 50+ countries | Hiking & adventure | LA",
    profilePicUrl: "https://i.pravatar.cc/150?img=22",
    location: "Los Angeles, CA",
    audienceAgeRange: "20-35",
    audienceGender: "52% Female, 48% Male",
    audienceLocation: "US 58%, UK 10%, Australia 8%",
    contentTypes: JSON.stringify(["reels", "posts", "stories"]),
    pastBrands: JSON.stringify(["Osprey", "Away", "Hostelworld", "World Nomads"]),
    tags: JSON.stringify(["travel", "adventure", "backpacking", "wanderlust", "hiking", "explore"]),
    priceRange: "400-1200",
    isVerified: true,
  },

  // Mental Health & Wellness
  {
    instagramHandle: "mindful_with_grace",
    name: "Grace Thompson",
    niche: "Mental Health & Wellness",
    subNiche: "Anxiety & Stress",
    followerCount: 189000,
    followingCount: 1034,
    engagementRate: 4.3,
    avgLikes: 8127,
    avgComments: 623,
    avgShares: 445,
    bio: "Licensed therapist | Mental health advocate | Anxiety management | Self-care routines | Boston",
    profilePicUrl: "https://i.pravatar.cc/150?img=28",
    location: "Boston, MA",
    audienceAgeRange: "22-40",
    audienceGender: "82% Female",
    audienceLocation: "US 71%, Canada 11%, UK 8%",
    contentTypes: JSON.stringify(["posts", "reels", "stories"]),
    pastBrands: JSON.stringify(["Calm", "Headspace", "Aura Health", "BetterHelp"]),
    tags: JSON.stringify(["mentalhealth", "wellness", "selfcare", "anxiety", "therapy", "mindfulness"]),
    priceRange: "300-800",
    isVerified: true,
  },
];

async function main() {
  console.log("Seeding influencer database...");

  for (const inf of influencers) {
    await prisma.influencer.upsert({
      where: { instagramHandle: inf.instagramHandle },
      update: inf,
      create: inf,
    });
  }

  console.log(`✓ Seeded ${influencers.length} influencers`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
